### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by kilianc** [kilianc/shared-git-hooks#1]
```
fs.js:945
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EEXIST: file already exists, symlink '/app/node_modules/shared-git-hooks/hook.sh' -> '/app/.git/hooks/pre-push'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at Object.installHook (/app/node_modules/shared-git-hooks/index.js:43:6)
    at /app/node_modules/shared-git-hooks/index.js:73:39
    at Array.forEach (native)
    at installHooks (/app/node_modules/shared-git-hooks/index.js:73:9)
    at Object.<anonymous> (/app/node_modules/shared-git-hooks/index.js:89:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by kilianc** [comment]
This happens when the folder containing the project is a link. this tricks https://github.com/kilianc/shared-git-hooks/blob/develop/index.js#L59 in thinking it's already installed.

**Comment by joh-klein** [comment]
I get the following error when I try to install it under Windows

```
fs.js:945
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink 'app\node_modules\shared-git-hooks\hook.sh' -> 'app\.git\hooks\applypatch-msg'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:945:18)
    at Object.installHook (app\node_modules\shared-git-hooks\index.js:43:6)
    at app\node_modules\shared-git-hooks\index.js:73:39
    at Array.forEach (native)
    at installHooks (app\node_modules\shared-git-hooks\index.js:73:9)
    at Object.<anonymous> (app\node_modules\shared-git-hooks\index.js:89:3)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
```

**Comment by kilianc** [comment]
@joh-klein I didn't even test this on windows, but at first sight it looks like a generic error: https://github.com/nodejs/node-v0.x-archive/issues/6342

Windows is not meant to be supported but I'll be happy to accept a PR
