### ISSUE TITLE
Error with node 0.10.32 (win32)

### ISSUE THREAD

**Issue by joh-klein** [kilianc/shared-git-hooks#3]
```
const fs = require('fs')
^^^^^
SyntaxError: Use of const in strict mode.
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:906:3
```

Fix: probably none :)
But you could maybe mention, that it needs a newer node version.

**Comment by kilianc** [comment]
Thanks @joh-klein ! I can probably specify the engine in the package and a little warning in the read me doesn't hurt.
